### ISSUE TITLE
Mini project 역할분담

### ISSUE THREAD

**Issue by jeeyunryu** [aidanbae0201/groupminiproject#3]
- [ ] Mini project 역할분담

1. 기획
2. 개발
3.  디자인

**Comment by aidanbae0201** [comment]
저희 기획은 같이 하고 개발 (함수 10개)는 50%씩 분담하고 wiki 페이지는 제가 만드는 쪽으로 생각했는데 어떠신가요??

**Comment by jeeyunryu** [comment]
네 좋은 것 같습니다. 함수 같은 경우는 구체적으로 설계를 한 후 같은 것 끼리 묵어 다시 나누면 좋을 것 같습니다.

**Comment by aidanbae0201** [comment]
넵 알겠습니다 :)
