### ISSUE TITLE
함 수 설 계

### ISSUE THREAD

**Issue by jeeyunryu** [aidanbae0201/groupminiproject#4]
- [ ] 추가로 구현할 함수 3개 정하기

**Comment by jeeyunryu** [comment]
기존의 구현해야 할 함수를 정리해보았습니다.
- CRUD
- list (자료 배열로 불러오는 기능의 함수)
- Load Data
- Save Data
- Menu 불러오기

**Comment by jeeyunryu** [comment]
각 함수의 기능을 생각해보면 좋을 것 같습니다.

**Comment by jeeyunryu** [comment]
> 기존의 구현해야 할 함수를 정리해보았습니다.
> 
> * CRUD
> * list (자료 배열로 불러오는 기능의 함수)
> * Load Data
> * Save Data

**Comment by jeeyunryu** [comment]
> 각 함수의 기능을 생각해보면 좋을 것 같습니다.

Create : 히딩크 구장 대여 신청 (정보 입력)
Read/List : 대여 신청 현황 확인
Update : 대여 신청 시 작성했던 정보 수정
Delete : 대여 신청 취소
Load Data : 
Save Data :
Menu : 시작 메뉴 불러오기

**Comment by jeeyunryu** [comment]
> * [ ]  추가로 구현할 함수 정하기

- 나의 예약 이력 확인하기
- No-show 횟수 누적하기

**Comment by jeeyunryu** [comment]
reserve.h에 정의된 함수의 기능을 설명해주세요

void printCalendar(Reserve *r[], int count, int month);
void searchNop(Reserve *r[],int count);
void searchStid(Reserve *r[],int count);
void saveFile(Reserve *r[], int count);
void addReserve(Reserve *r[], int count);

**Comment by jeeyunryu** [comment]
일단 전 이렇게 생각해 보았습니다.
- CreateReservation() : 히딩크 구장 대여 신청 (정보 입력)
- ReadReservation() /ListReservation()  : 대여 신청 현황 확인
- UpdateReservation() : 대여 신청 시 작성했던 정보 수정
- DeleteReservation() : 대여 신청 취소
- LoadData() : 대여 신청에 대한 Data 저장하기
- SaveData() : 저장된 Data 불러오기
- LoadMenu() : 시작 메뉴 불러오기
- 나의 예약 이력 확인하기
- No-show 횟수 누적하기

**Comment by aidanbae0201** [comment]
제가 함수 몇개 작성 끝났는데 직접 작업하고 싶으신 함수들 알려주시면 나머지를 제가 하도록 하겠습니다~~

**Comment by jeeyunryu** [comment]
구현 되지 않은 함수 list

- [x] Search Student id
- [x] Search Number of People
- [x] Check No Show
- [x] Save file
- [x] Load file
- [x] Choose Number
- [x] Update Reserve

**Comment by jeeyunryu** [comment]
checkNoShow() 함수 코드 작성 중입니다.

**Comment by aidanbae0201** [comment]
함수 구현 완료했습니다
중간에 listReserve() 함수와 readReserve()함수를 추가해야할 것 같아서 추가했습니다!
